version: "3.9"
services:
  backend:
    image: '#image'
    container_name: healthcheck
    restart: always
    ports:
      - "80:2024"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 2024
      POSTGRES_DB: jdbc:postgresql://database:5432/postgres
      POSTGRES_USER: healthcheckuser
      POSTGRES_PASSWORD: healthcheck11

  activemq:
    image: rmohr/activemq:5.14.0
    container_name: activemq
    ports:
      - "61616:61616"
    environment:
      ACTIVEMQ_CONFIG_NAME: "amqp"
      ACTIVEMQ_CONFIG_DEFAULTACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_ADMIN_PASSWORD: "admin"
      ACTIVEMQ_CONFIG_QUEUES: "pdfQueue"

  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: healthcheckuser
      POSTGRES_PASSWORD: healthcheck11
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: